version: 2
jobs:
  build:
    working_directory: /go/src/gopkg.in/webnice/migrate.v1/gsmigrate
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run: go get -t -d -v ./...
      - run: make dep
      - run: make test
